"""new migration

Revision ID: a2cdeccc618c
Revises: d7fd59bea9dc
Create Date: 2024-06-06 18:10:07.658849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2cdeccc618c'
down_revision: Union[str, None] = 'd7fd59bea9dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_us',
    sa.Column('title_en', sa.String(length=100), nullable=False),
    sa.Column('title_kg', sa.String(length=100), nullable=False),
    sa.Column('title_ru', sa.String(length=100), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_kg', sa.Text(), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_about_us'))
    )
    op.create_table('center_banners',
    sa.Column('title_en', sa.String(length=100), nullable=False),
    sa.Column('title_kg', sa.String(length=100), nullable=False),
    sa.Column('title_ru', sa.String(length=100), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('description_kg', sa.Text(), nullable=True),
    sa.Column('description_ru', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_center_banners'))
    )
    op.create_table('consultation_requests',
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('agree_to_privacy_policy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation_requests'))
    )
    op.create_table('contacts',
    sa.Column('branches', sa.Text(), nullable=True),
    sa.Column('funding_points', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    op.create_table('financial_reports',
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('title_kg', sa.String(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=False),
    sa.Column('description_en', sa.String(), nullable=True),
    sa.Column('description_kg', sa.String(), nullable=True),
    sa.Column('description_ru', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_reports'))
    )
    op.create_table('general_requests',
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('agree_to_privacy_policy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_general_requests'))
    )
    op.create_table('job_applications',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('attachment', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_applications'))
    )
    op.create_table('mudaraba_calculators',
    sa.Column('deposit_type', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mudaraba_calculators'))
    )
    op.create_table('news',
    sa.Column('title_en', sa.String(length=100), nullable=False),
    sa.Column('title_kg', sa.String(length=100), nullable=False),
    sa.Column('title_ru', sa.String(length=100), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('text_kg', sa.Text(), nullable=False),
    sa.Column('text_ru', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news'))
    )
    op.create_table('partners',
    sa.Column('title_en', sa.String(length=100), nullable=False),
    sa.Column('title_kg', sa.String(length=100), nullable=False),
    sa.Column('title_ru', sa.String(length=100), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_kg', sa.Text(), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partners'))
    )
    op.create_table('partnership_requests',
    sa.Column('contact_person', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('product_group', sa.String(length=100), nullable=False),
    sa.Column('agree_to_privacy_policy', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partnership_requests'))
    )
    op.create_table('products',
    sa.Column('title_en', sa.String(length=100), nullable=False),
    sa.Column('title_kg', sa.String(length=100), nullable=False),
    sa.Column('title_ru', sa.String(length=100), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_kg', sa.Text(), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('profit_norms',
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('title_kg', sa.String(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=False),
    sa.Column('description_en', sa.String(), nullable=True),
    sa.Column('description_kg', sa.String(), nullable=True),
    sa.Column('description_ru', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profit_norms'))
    )
    op.create_table('question_requests',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('attachment', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_question_requests'))
    )
    op.create_table('sharia_council',
    sa.Column('fullname', sa.String(length=100), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_kg', sa.Text(), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sharia_council'))
    )
    op.create_table('vacancies',
    sa.Column('title_en', sa.String(length=100), nullable=False),
    sa.Column('title_kg', sa.String(length=100), nullable=False),
    sa.Column('title_ru', sa.String(length=100), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_kg', sa.Text(), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancies'))
    )
    op.drop_index('ix_ifc_news_id', table_name='ifc_news')
    op.drop_index('ix_ifc_news_title', table_name='ifc_news')
    op.drop_table('ifc_news')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ifc_news',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('video', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ifc_news_pkey')
    )
    op.create_index('ix_ifc_news_title', 'ifc_news', ['title'], unique=False)
    op.create_index('ix_ifc_news_id', 'ifc_news', ['id'], unique=False)
    op.drop_table('vacancies')
    op.drop_table('sharia_council')
    op.drop_table('question_requests')
    op.drop_table('profit_norms')
    op.drop_table('products')
    op.drop_table('partnership_requests')
    op.drop_table('partners')
    op.drop_table('news')
    op.drop_table('mudaraba_calculators')
    op.drop_table('job_applications')
    op.drop_table('general_requests')
    op.drop_table('financial_reports')
    op.drop_table('contacts')
    op.drop_table('consultation_requests')
    op.drop_table('center_banners')
    op.drop_table('about_us')
    # ### end Alembic commands ###
