"""create ifcnews table

Revision ID: d7fd59bea9dc
Revises: 
Create Date: 2024-06-03 09:22:43.252128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7fd59bea9dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ifc_news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('video', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ifc_news_id'), 'ifc_news', ['id'], unique=False)
    op.create_index(op.f('ix_ifc_news_title'), 'ifc_news', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ifc_news_title'), table_name='ifc_news')
    op.drop_index(op.f('ix_ifc_news_id'), table_name='ifc_news')
    op.drop_table('ifc_news')
    # ### end Alembic commands ###
